/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_LPUART0RXSRC_0b0 0x00u  /*!<@brief LPUART0 Receive Data Source Select: LPUART_RX pin */
#define SOPT5_LPUART0TXSRC_0b00 0x00u /*!<@brief LPUART0 Transmit Data Source Select: LPUART0_TX pin */

/*! @name PORTC6 (number 42), LPUART0_RX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITLPUART_LPUART0_RX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLPUART_LPUART0_RX_PIN 6U                   /*!<@brief PORT pin number */
#define BOARD_INITLPUART_LPUART0_RX_PIN_MASK (1U << 6U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*! @name PORTC7 (number 43), LPUART0_TX
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITLPUART_LPUART0_TX_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITLPUART_LPUART0_TX_PIN 7U                   /*!<@brief PORT pin number */
#define BOARD_INITLPUART_LPUART0_TX_PIN_MASK (1U << 7U)      /*!<@brief PORT pin mask */
                                                             /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLPUART(void);

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitLEDs(void);

/*! @name PORTB18 (number 23), SW2
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW2_FGPIO FGPIOB              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_GPIO GPIOB                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_GPIO_PIN_MASK (1U << 18U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW2_PORT PORTB                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW2_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW2_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name PORTC2 (number 38), SW3
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITBUTTONS_SW3_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_GPIO_PIN_MASK (1U << 2U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITBUTTONS_SW3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITBUTTONS_SW3_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITBUTTONS_SW3_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitButtons(void);

/*! @name PORTC3 (number 39), PTC3
  @{ */

/* Symbols to be used with GPIO driver */
#define PTC3_INPUTINIT_PTC3_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define PTC3_INPUTINIT_PTC3_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define PTC3_INPUTINIT_PTC3_GPIO_PIN_MASK (1U << 3U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PTC3_INPUTINIT_PTC3_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define PTC3_INPUTINIT_PTC3_PIN 3U                   /*!<@brief PORT pin number */
#define PTC3_INPUTINIT_PTC3_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTC3_InputInit(void);

/*! @name PORTB2 (number 18), LED_B
  @{ */

/* Symbols to be used with PORT driver */
#define PTB2_ADCINIT_LED_B_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define PTB2_ADCINIT_LED_B_PIN 2U                   /*!<@brief PORT pin number */
#define PTB2_ADCINIT_LED_B_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTB2_ADCInit(void);

/*! @name PORTB3 (number 19), LIGHT
  @{ */

/* Symbols to be used with PORT driver */
#define PTB3_ADCINIT_LIGHT_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define PTB3_ADCINIT_LIGHT_PIN 3U                   /*!<@brief PORT pin number */
#define PTB3_ADCINIT_LIGHT_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTB3_ADCInit(void);

/*! @name PORTC4 (number 40), DOOR
  @{ */

/* Symbols to be used with GPIO driver */
#define DOOR_INPUT_DOOR_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define DOOR_INPUT_DOOR_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define DOOR_INPUT_DOOR_GPIO_PIN_MASK (1U << 4U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define DOOR_INPUT_DOOR_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define DOOR_INPUT_DOOR_PIN 4U                   /*!<@brief PORT pin number */
#define DOOR_INPUT_DOOR_PIN_MASK (1U << 4U)      /*!<@brief PORT pin mask */
                                                 /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Door_Input(void);

/*! @name PORTA16 (number 4), RELAY1_1
  @{ */

/* Symbols to be used with GPIO driver */
#define PTA16_INIT_RELAY1_1_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define PTA16_INIT_RELAY1_1_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define PTA16_INIT_RELAY1_1_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PTA16_INIT_RELAY1_1_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define PTA16_INIT_RELAY1_1_PIN 16U                   /*!<@brief PORT pin number */
#define PTA16_INIT_RELAY1_1_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTA16_Init(void);

/*! @name PORTC1 (number 37), RELAY1_2
  @{ */

/* Symbols to be used with GPIO driver */
#define PTC1_INIT_RELAY1_2_FGPIO FGPIOC             /*!<@brief FGPIO peripheral base pointer */
#define PTC1_INIT_RELAY1_2_GPIO GPIOC               /*!<@brief GPIO peripheral base pointer */
#define PTC1_INIT_RELAY1_2_GPIO_PIN_MASK (1U << 1U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PTC1_INIT_RELAY1_2_PORT PORTC               /*!<@brief PORT peripheral base pointer */
#define PTC1_INIT_RELAY1_2_PIN 1U                   /*!<@brief PORT pin number */
#define PTC1_INIT_RELAY1_2_PIN_MASK (1U << 1U)      /*!<@brief PORT pin mask */
                                                    /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTC1_Init(void);

/*! @name PORTA19 (number 7), RELAY2_1
  @{ */

/* Symbols to be used with GPIO driver */
#define PTA19_INIT_RELAY2_1_FGPIO FGPIOA              /*!<@brief FGPIO peripheral base pointer */
#define PTA19_INIT_RELAY2_1_GPIO GPIOA                /*!<@brief GPIO peripheral base pointer */
#define PTA19_INIT_RELAY2_1_GPIO_PIN_MASK (1U << 19U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PTA19_INIT_RELAY2_1_PORT PORTA                /*!<@brief PORT peripheral base pointer */
#define PTA19_INIT_RELAY2_1_PIN 19U                   /*!<@brief PORT pin number */
#define PTA19_INIT_RELAY2_1_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTA19_Init(void);

/*! @name PORTC16 (number 45), RELAY2_2
  @{ */

/* Symbols to be used with GPIO driver */
#define PTC16_INIT_RELAY2_2_FGPIO FGPIOC              /*!<@brief FGPIO peripheral base pointer */
#define PTC16_INIT_RELAY2_2_GPIO GPIOC                /*!<@brief GPIO peripheral base pointer */
#define PTC16_INIT_RELAY2_2_GPIO_PIN_MASK (1U << 16U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define PTC16_INIT_RELAY2_2_PORT PORTC                /*!<@brief PORT peripheral base pointer */
#define PTC16_INIT_RELAY2_2_PIN 16U                   /*!<@brief PORT pin number */
#define PTC16_INIT_RELAY2_2_PIN_MASK (1U << 16U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PTC16_Init(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
